[package]
name = "neohertz/neocache"
description = "A powerful caching system for any item you'd ever desire."
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
